version: "3.8"

services:
  app-scraper:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ghcr.io/yasir-khalid/tradovate-price-scraper:latest
    platform: linux/amd64
    container_name: tradovate-price-streamer
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge